[platformio]
extra_configs = ../pio-common.ini
src_dir = .

[chip]
#extends = g431k
extends = f407deb

[env:add]
extends = chip
[env:del]
extends = chip
[env:dump]
extends = chip
[env:flash]
extends = chip
[env:format]
extends = chip
[env:list]
extends = chip
[env:show]
extends = chip
