[platformio]
extra_configs = ../pio-common.ini
src_dir = .

[env]
#extends = g431k
extends = l432k
monitor_speed = 1000000

[env:blink]
[env:pins]
[env:tracer]
[env:lptimer]

[trace]
build_flags = ${env.build_flags} -DTRACE -I.

[env:wait]
extends = trace
[env:coma]
extends = trace
[env:stop]
extends = trace
[env:thread]
extends = trace
[env:rctimer]
extends = trace
[env:exti]
extends = trace
