[platformio]
src_dir = .

[env]
platform = ststm32
framework = cmsis
board = nucleo_g431kb
board_leds = B8
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror
build_src_filter = +<${PIOENV}.cpp>
lib_deps = symlink://../..

[env:blink]
[env:pins]
[env:tracer]

[trace]
build_flags = ${env.build_flags} -DTRACE -I.

[env:wait]
extends = trace
[env:coma]
extends = trace
[env:thread]
extends = trace
