[platformio]
src_dir = .

[env]
platform = ststm32
framework = cmsis
board = genericSTM32F103C8
board_leds = A1
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror
build_src_filter = +<${PIOENV}.cpp>
lib_deps = symlink://../..

[env:blink]
[env:pins]
[env:tracer]
