#!/bin/sh

# Collect all the IRQ handler names in all the installed CMSIS packages in PIO.
# This will only be a complete list if all CMSIS families are actually present.
# The output should be saved as "all-irqs.h".

echo "// This header was auto-generated by gen-irqs.sh - do not edit."
echo

for i in \
    ~/.platformio/packages/framework-cmsis-*/Source/Templates/gcc/ \
    /home/src/jeeh/cmsis_device_*/Source/Templates/gcc/
do
    echo $i >&2
    cd $i
    grep -h '\.word.*Handler' *.s *.S | awk '{ print "IRQ(", $2, ")" }'
done | sort -u

echo
echo "// End of auto-generated header."
