[platformio]
src_dir = ../g431k

[env]
platform = ststm32
framework = cmsis
build_src_filter = +<${PIOENV}.cpp>
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror -Wno-format
lib_deps = symlink://../..
board = nucleo_l432kc
board_leds = A0
board_pins = vcc:B1 bmp:A11 lcd:A12 sram:B0 sd:A7
board_uart = N:USART2 P:A2:7,A15:3 F:80 D:1 L:CH T:7 R:6 C:2,2 O:1
board_spi = N:SPI1 P:B5:H5,B4,B3,A11:HP F:80 D:1 L:CH T:3 R:2 C:1,1 O:1
board_i2c = N:I2C1 P:B7:OH4,B6 F:80 D:2 L:CH T:7 R:6 C:5,5 O:1
monitor_speed = 2000000

[env:serial]
[env:scan]
[env:dog]
[env:oled]
[env:imu]
[env:pulses]
[env:bmp390i]
[env:bmp390s]
[env:fram]
[env:sram]
[env:sht21]
[env:lcd]
[env:sdspi]
[env:shell]
