[platformio]
extra_configs = ../pio-common.ini
src_dir = .

[env]
extends = common

[f429hy]
upload_protocol = jlink
#upload_flags = -c, adapter serial 066EFF565251887067065644
#monitor_port = hwgrep://066EFF565251887067065644

[env:font]
extends = f429hy

[env:gpio]
extends = f429hy

[env:life]
extends = f429hy

[env:ram]
extends = f429hy
