[platformio]
extra_configs = ../etc/common.ini
src_dir = ../../old-tests/basic

[env]
extends = common
board = nucleo_g474re
board_exti = IN:C5 OUT:C4
board_leds = A5
#board_uart = N:USART2 P:A2:7,A3 F:170 D:1 L:CH T:1 R:2 C:27,26 O:1
board_uart = N:USART1 P:C4:7,C5 F:170 D:1 L:CH T:1 R:2 C:25,24 O:1
board_build.f_cpu = 170000000
build_flags = ${common.build_flags} -DXTAL=24
