[platformio]
extra_configs = ../etc/common.ini
src_dir = ../../tests/basic

[env]
platform_packages = platformio/tool-pyocd
debug_tool = custom
extends = common
board = nucleo_h743zi
board_exti = G9 G14
board_leds = B0 B7 B14
#board_uart = N=USART3 P=D8:7,D9 F=120 D=1 L=Stream T=1 R=2 C=27,26
board_uart = N=USART6 P=G14:7,G9 F=120 D=1 L=Stream T=1 R=2 C=115,114
board_build.f_cpu = 400000000
build_flags = ${common.build_flags} -DXTAL=0
#upload_protocol = cmsis-dap
upload_command = st-flash --reset write $SOURCE 0x20000200
