[platformio]
extra_configs = ../pio-common.ini
src_dir = .

[env]
extends = l432k
upload_flags = -c, adapter serial 0669FF555052836687022922
monitor_port = hwgrep://0669FF555052836687022922

[env:blink]
[env:stop]
[env:alarm]
[env:coma]
[env:minimal]
