[platformio]
src_dir = .

[env]
platform = ststm32
framework = cmsis
board = nucleo_l412rb_p
board_leds = B13
build_src_filter = +<${PIOENV}.cpp>
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror -DMYSYSTICK
lib_deps = symlink://../..
monitor_speed = 1000000

[env:blink]
[env:signal]
[env:cycle]
[env:rtc]
[env:push]
[env:convol]
[env:lptimer]
[env:systick]
