[platformio]
src_dir = .

[env]
platform = ststm32
framework = cmsis
board = disco_l496ag
board_leds = A5 B13
build_src_filter = +<${PIOENV}.cpp>
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror
lib_deps = symlink://../..
monitor_speed = 2000000

[env:blink]
[env:signal]
[env:pulses]
