[platformio]
src_dir = .
extra_configs = pio-local.ini

[env]
platform = ststm32
framework = cmsis
board = blackpill_f411ce
lib_deps = jcw/jeeh@7
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror -Wno-format
build_src_filter = +<${PIOENV}.cpp>
monitor_speed = 2000000

[env:scan]
[env:sht21]
[env:fram]

[env:scan-poll]
[env:sht21-poll]
[env:fram-poll]
