[platformio]
extra_configs = ../attached.ini, ../boards.ini
src_dir = .

[env]
platform = ststm32
framework = cmsis

# all environments are listed in attached.ini and boards.ini
# this file only adds settings which differ

[env:wl55r]
build_flags = -DCORE_CM4
