[platformio]
extra_configs = ../etc/common.ini
src_dir = ../../old-tests/basic

[env]
extends = common
board = nucleo_f413zh
board_exti = IN:G14 OUT:G9
board_leds = B0
#board_uart = N:USART3 P:D8:7,D9 F:50 D:1 L:Stream T:3 R:1 C:4,4
board_uart = N:USART6 P:G14:8,G9 F:100 D:2 L:Stream T:6 R:2 C:5,5
board_build.f_cpu = 100000000
