[platformio]
src_dir = ../../tests/basic

[env]
platform = ststm32
framework = cmsis

board = disco_f723ie
board_exti = A3 A2
board_leds = A5
board_uart = N=USART6 P=C6:8,C7 F=108 D=2 L=Stream T=2 R=6 C=5,5

board_build.f_cpu = 216000000
board_build.ldscript = ram.ld
build_src_filter = +<${PIOENV}-*.cpp>
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror -Wno-format -g -DXTAL=25
lib_deps = symlink://../..
upload_protocol = custom
monitor_speed = 115200
extra_scripts = post:pio-extra.py

[env:t00]
[env:t01]
[env:t02]
[env:t03]
[env:t04]
[env:t05]
[env:t06]
[env:t07]
[env:t08]
[env:t09]
[env:t10]
[env:t11]
[env:t12]
[env:t13]
[env:t14]
[env:t15]
[env:t16]
[env:t17]
[env:t18]
[env:t19]
[env:t20]
