[platformio]
extra_configs = ../etc/common.ini
src_dir = ../../tests/basic

[env]
extends = common
board = disco_f723ie
board_exti = A3 A2
board_leds = A5
#board_uart = N=USART6 P=C6:8,C7 F=108 D=2 L=Stream T=6 R=2 C=5,5
board_uart = N=USART2 P=A2:7,A3 F=108 D=1 L=Stream T=6 R=5 C=4,4
board_build.f_cpu = 216000000
build_flags = ${common.build_flags} -DXTAL=25

[env:i2c]
