[platformio]
src_dir = .

[env:rtt]
platform = ststm32
framework = cmsis
#board = nucleo_l073rz
board = disco_l053c8
build_flags = -std=c++17 -Wall -Werror -Wno-format
lib_deps = symlink://../..
#board_leds = A5
board_leds = B5
