[platformio]
src_dir = .

[env]
platform = ststm32
framework = cmsis
build_src_filter = +<${PIOENV}.cpp>
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror -Wno-format
              -DMAX_EVENTS=25
lib_deps = symlink://../..
board = nucleo_l011k4
board_leds = B3
board_uart = N:USART2 P:A2:U4,A3 F:32 D:1 L:Channel T:4 R:5 C:4,4 O:1
monitor_speed = 115200

[env:blink]
[env:tick]
