[platformio]
extra_configs = ../etc/common.ini
src_dir = ../../tests/basic

[env]
extends = common
board = disco_l475vg_iot01a
board_exti = IN:A1 OUT:A0
board_leds = A5
#board_uart = N:USART1 P:B6:7,B7 F:80 D:2 L:Channel T:6 R:7 C:2,2 O:1
board_uart = N:UART4 P:A0:8,A1 F:80 D:2 L:Channel T:3 R:5 C:2,2 O:1
board_build.f_cpu = 80000000

[env:i2c]
