[platformio]
extra_configs = ../pio-common.ini
src_dir = .

[env]
extends = common

[send]
build_src_filter = +<send.cpp>
[env:send-poll]
extends = send, g474r, poll
[env:send-sync]
extends = send, g474r, sync
[env:send-call]
extends = send, g474r, call
