[platformio]
src_dir = .
monitor_dir = .

[env]
platform = ststm32
framework = cmsis
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror -Wno-format
lib_deps = symlink://../..
monitor_filters = time

debug_extra_cmds =
  mon set fcpu ${this.board_build.f_cpu}
  mon $_CHIPNAME.tpiu configure -protocol uart -formatter false -output :6464 \
        -traceclk $fcpu -pin-freq [expr {$fcpu/8}]
  mon $_CHIPNAME.tpiu enable
  mon itm ports on

[env:g431k]
board = nucleo_g431kb
build_flags = ${env.build_flags} -DXTAL=0 -DLED='"B8"'
board_build.f_cpu = 150000000

#[env:g431r]
#board = nucleo_g431rb
#build_flags = ${env.build_flags} -DXTAL=24 -DLED='"A5"'
#board_build.f_cpu = 150000000
