[platformio]
extra_configs = ../etc/common.ini
src_dir = ../../tests/basic

[env]
extends = common
board = disco_l496ag
board_exti = A1 A0
board_leds = B13 A5
#board_uart = N=LPUART1 P=G7:7,G8 F=80 D=2 L=CH T=6 R=7 C=4,4 O=1
board_uart = N=UART4 P=A0:8,A1 F=80 D=2 L=CH T=3 R=5 C=2,2 O=1
board_build.f_cpu = 80000000

[env:i2c]
