[platformio]
extra_configs = ../etc/common.ini
src_dir = ../../tests/basic

[env]
extends = common
board_build.ldscript =
upload_protocol = stlink
extra_scripts =

board = nucleo_l031k6
board_exti = A10 A9
board_leds = B3
#board_uart = N=USART2 P=A2:4,A3 F=32 D=1 L=Channel T=4 R=5 C=4,4 O=1
board_uart = N=USART2 P=A9:4,A10 F=32 D=1 L=Channel T=4 R=5 C=4,4 O=1
board_build.f_cpu = 32000000
