[platformio]
# re-use the settings from all-blink and all-tick
extra_configs = ../all-tick/platformio.ini

# ....d = Discovery boards
# ....k = Nucleo-32 boards
# ....r = Nucleo-64 boards
# ....z = Nucleo-144 boards
