[platformio]
extra_configs = ../etc/common.ini
src_dir = ../../old-tests/basic

[env]
extends = common
board = bluepill_f103c8
board_exti = IN:A3 OUT:A2
board_leds = C13
#board_uartc = N:USART1 P:A9:7,A10 F:72 D:1 L:Channel T:4 R:5 C:0,0 O:1
board_uartc = N:USART1 P:A9:7,A10 F:72
board_uart = N:USART2 P:A2:7,A3 F:36 D:1 L:Channel T:7 R:6 C:0,0 O:1
board_build.f_cpu = 72000000
upload_protocol = blackmagic
monitor_port = /dev/cu.usbmodem80A978D63
