#!/usr/bin/env python3

# generate "attached.ini" (Linux only) and "boards.ini" (always)
# uses "boards.csv" and looks at current devices in /dev/serial/by-id/
# returns the list of attached boards as output, for use as arg to "make"

import csv, os

with open('boards.csv') as f:
    boards = [r for r in csv.reader(f)]
#print(boards)

template1 = '''
[env:%s]
board = %s'''

seen = set()
with open('boards.ini', 'w') as f:
    print('# Generated by attached.py', file=f)
    for e, s, b in boards:
        if e not in seen:
            print(template1 % (e, b), file=f)
            seen.add(e)
#print(sorted(seen))

template2 = '''
[env:%s]
board = %s
board_serial = %s
upload_flags = -c, adapter serial ${board_serial}'''

DEVS = '/dev/serial/by-id/'
found = set()
if os.path.exists(DEVS):
    with open('attached.ini', 'w') as f:
        print('# Generated by attached.py', file=f)
        attached = []
        for d in os.listdir(DEVS):
            for e, s, b in boards:
                if s in d:
                    attached.append((e, s, b))
                    found.add(e)
                    break
        for e, s, b in sorted(attached):
            print(template2 % (e, b, s), file=f)
print(' '.join(sorted(found)))
