# Common config for PlatformIO, see */platformio.ini files.

[common]
platform = ststm32
framework = cmsis
board_build.ldscript = ../etc/common.ld
build_src_filter = +<${PIOENV}-*.cpp>
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror -Wno-format -g
lib_deps = symlink://../..
upload_protocol = custom
monitor_speed = 115200
extra_scripts = post:../etc/pio-check.py

[env:t00]
[env:t01]
[env:t02]
[env:t03]
[env:t04]
[env:t05]
[env:t06]
[env:t07]
[env:t08]
[env:t09]
[env:t10]
[env:t11]
[env:t12]
[env:t13]
[env:t14]
[env:t15]
[env:t16]
[env:t17]
[env:t18]
[env:t19]
[env:t20]
[env:t21]
