[platformio]
extra_configs = ../pio-common.ini
src_dir = .

[detect]
build_src_filter = +<detect.cpp>
[env:detect-gpio]
extends = detect, g431k, gpio
[env:detect-poll]
extends = detect, g431k, poll
[env:detect-sync]
extends = detect, g431k, sync
[env:detect-call]
extends = detect, g431k, call

[env:detect-l412k]
extends = detect, l412k, poll

[fram]
build_src_filter = +<fram.cpp>
[env:fram-gpio]
extends = fram, g431k, gpio
[env:fram-poll]
extends = fram, g431k, poll
[env:fram-sync]
extends = fram, g431k, sync
[env:fram-call]
extends = fram, g431k, call

[imu]
build_src_filter = +<imu.cpp>
[env:imu-gpio]
extends = imu, l412k, gpio
[env:imu-poll]
extends = imu, l412k, poll
[env:imu-sync]
extends = imu, l412k, sync
[env:imu-call]
extends = imu, l412k, call

[oled]
build_src_filter = +<oled.cpp>
[env:oled-gpio]
extends = oled, l412k, gpio
[env:oled-poll]
extends = oled, l412k, poll
[env:oled-sync]
extends = oled, l412k, sync
[env:oled-call]
extends = oled, l412k, call

[rtc]
build_src_filter = +<rtc.cpp>
[env:rtc-gpio]
extends = rtc, l412k, gpio
[env:rtc-poll]
extends = rtc, l412k, poll
[env:rtc-sync]
extends = rtc, l412k, sync
[env:rtc-call]
extends = rtc, l412k, call
