[platformio]
src_dir = .

[env]
platform = ststm32
framework = cmsis
build_src_filter = +<${PIOENV}.cpp>
build_flags = -std=c++17 -Wall -Werror -Wno-format
lib_deps = symlink://../..
monitor_speed = 115200

# BOARDS

[g431k]
board = nucleo_g431kb
build_flags = ${env.build_flags} -DXTAL=0
board_leds = B8
board_uart = N:USART2 P:A2:UH7,A3 F:170 D:1 L:CH T:1 R:2 C:27,26 O:1
board_i2c = N:I2C1 P:B7:OH4,A15 F:170 D:1 L:CH T:3 R:4 C:17,16 O:1

[l432k]
board = nucleo_l432kc
board_leds = B3
board_uart = N:USART2 P:A2:7,A15:3 F:80 D:1 L:CH T:7 R:6 C:2,2 O:1
board_i2c = N:I2C1 P:B7:OH4,B6 F:80 D:2 L:CH T:7 R:6 C:5,5 O:1

# MODES

[gpio]
board_mode = gpio
[poll]
board_mode = poll
[sync]
board_mode = sync
[call]
board_mode = call

# APPS

[detect]
build_src_filter = +<detect.cpp>
[fram]
build_src_filter = +<fram.cpp>
[imu]
build_src_filter = +<imu.cpp>
[oled]
build_src_filter = +<oled.cpp>

# BUILD TARGETS

[env:detect]
extends = g431k, detect

[env:fram-gpio]
extends = g431k, fram, gpio
[env:fram-poll]
extends = g431k, fram, poll
[env:fram-sync]
extends = g431k, fram, sync
[env:fram-call]
extends = g431k, fram, call

[env:imu-gpio]
extends = l432k, imu, gpio
[env:imu-poll]
extends = l432k, imu, poll
[env:imu-sync]
extends = l432k, imu, sync
[env:imu-call]
extends = l432k, imu, call

[env:oled-gpio]
extends = l432k, oled, gpio
[env:oled-poll]
extends = l432k, oled, poll
[env:oled-sync]
extends = l432k, oled, sync
[env:oled-call]
extends = l432k, oled, call
