[platformio]
extra_configs = ../pio-common.ini
src_dir = .

# APPS

[fram]
build_src_filter = +<fram.cpp>
[imu]
build_src_filter = +<imu.cpp>
[oled]
build_src_filter = +<oled.cpp>

# BUILD TARGETS

[env:detect]
extends = g431k, poll

[env:fram-gpio]
extends = g431k, fram, gpio
[env:fram-poll]
extends = g431k, fram, poll
[env:fram-sync]
extends = g431k, fram, sync
[env:fram-call]
extends = g431k, fram, call

[env:imu-gpio]
extends = l432k, imu, gpio
[env:imu-poll]
extends = l432k, imu, poll
[env:imu-sync]
extends = l432k, imu, sync
[env:imu-call]
extends = l432k, imu, call

[env:oled-gpio]
extends = l432k, oled, gpio
[env:oled-poll]
extends = l432k, oled, poll
[env:oled-sync]
extends = l432k, oled, sync
[env:oled-call]
extends = l432k, oled, call
