[platformio]
src_dir = .

[env]
platform = ststm32
framework = cmsis
board = nucleo_g474re
board_leds = A5
board_uart = N:USART2 P:A2:7,A3 F:170 D:1 L:CH T:1 R:2 C:27,26 O:1
board_build.f_cpu = 170000000
build_src_filter = +<${PIOENV}.cpp>
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror -Wno-format -DXTAL=24
lib_deps = symlink://../..
monitor_speed = 115200

[env:blink-wa]
build_src_filter = +<blink.cpp>
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror -Wno-format
board_leds = C6
upload_protocol = dfu

[env:blink]
[env:hello]
