[platformio]
src_dir = .

[env:rtt]
platform = ststm32
framework = cmsis
#board = nucleo_l073rz
#board = disco_l053c8
board = bluepill_f103c8
build_flags = -std=c++17 -Wall -Werror -Wno-format -g
lib_deps = symlink://../..
#board_leds = A5
#board_leds = B5
board_leds = C13
upload_protocol = blackmagic
