[platformio]
extra_configs = ../pio-common.ini
src_dir = .

[env]
extends = common

[env:blink]
extends = l412k, gpio

[i2c]
build_src_filter = +<i2c.cpp>
[env:i2c-gpio]
extends = i2c, l412k, gpio
[env:i2c-poll]
extends = i2c, l412k, poll
[env:i2c-sync]
extends = i2c, l412k, sync
[env:i2c-call]
extends = i2c, l412k, call

[spi]
build_src_filter = +<spi.cpp>
[env:spi-gpio]
extends = spi, l412k, gpio
[env:spi-poll]
extends = spi, l412k, poll
[env:spi-sync]
extends = spi, l412k, sync
[env:spi-call]
extends = spi, l412k, call
