[platformio]
extra_configs = ../pio-common.ini
src_dir = .

[env]
extends = common, l432k
build_flags = ${common.build_flags} -DTRACE -I.
upload_flags = -c, adapter serial 066EFF565251887067065644
monitor_port = hwgrep://066EFF565251887067065644
monitor_speed = 2000000

[env:blink]
[env:pins]
[env:tracer]
[env:lptimer]
[env:wait]
[env:coma]
[env:stop]
[env:thread]
[env:rctimer]
[env:exti]
