[platformio]
extra_configs = ../common.ini
src_dir = ../../tests/basic

[env]
extends = common
board = nucleo_l433rc_p
board_exti = A10 A9
board_leds = B13
#board_uart = N=USART2 P=A2:7,A3 F=80 D=1 L=Channel T=7 R=6 C=2,2 O=1
board_uart = N=USART1 P=A9:7,A10 F=80 D=1 L=Channel T=4 R=5 C=2,2 O=1
board_build.f_cpu = 80000000
