[platformio]
src_dir = .

[env]
platform = ststm32
framework = cmsis
build_src_filter = +<${PIOENV}.cpp>
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror -Wno-format -DXTAL=0
lib_deps = symlink://../..
# g431k
board = nucleo_g431kb
board_leds = B8
board_uart = N:USART1 P:A9:U7,A10 F:170 D:1 L:CH T:1 R:2 C:25,24 O:1
board_spi = N:SPI1 P:B5:H5,B4,B3,A11:HP F:170 D:1 L:CH T:3 R:4 C:11,10 O:1
board_i2c = N:I2C1 P:B7:OH4,A15 F:170 D:1 L:CH T:3 R:4 C:17,16 O:1
board_build.f_cpu = 160000000
monitor_speed = 10000000

[env:blink]
[env:fast]
[env:serial]
[env:i2c]
