[platformio]
# re-use the settings from 1-blink
extra_configs = ../1-blink/platformio.ini

[env]
monitor_speed = 2000000

# ....d = Discovery boards
# ....k = Nucleo-32 boards
# ....r = Nucleo-64 boards
# ....z = Nucleo-144 boards

[env:f103r]
board_uart = N:USART2 P:A2:U1,A3 F:36

[env:f103rc]
board_uart = N:UART5 P:C12:U1,D2 F:36

[env:f303k]
build_flags = ${env.build_flags} -DXTAL=0
board_uart = N:USART2 P:A2:7,A15 F:36

[env:f303o]
board_uart = N:USART3 P:B10:7,B11 F:36

[env:f303z]
board_uart = N:USART3 P:D8:7,D9 F:36

[env:f334r]
board_uart = N:USART2 P:A2:U7,A3 F:36

[env:f407d]
board_uart = N:USART2 P:A2:U7,A3 F:84

#[env:f401r]
#board_uart = N:USART2 P:A2:U7,A3 F:42

[env:f411bp]
board_uart = N:USART1 P:A9:U7,A10 F:100

[env:f411r]
board_uart = N:USART2 P:A2:U7,A3 F:50

[env:f412d]
board_uart = N:USART2 P:A2:U7,A3 F:50

[env:f446z]
board_uart = N:USART3 P:D8:7,D9 F:90

[env:f723d]
build_flags = ${env.build_flags} -DXTAL=25
board_uart = N:USART6 P:C6:8,C7 F:108

[env:f746z]
board_uart = N:USART3 P:D8:7,D9 F:90

[env:f750d]
build_flags = ${env.build_flags} -DXTAL=25
board_uart = N:USART1 P:A9:7,B7 F:108

[env:f767z]
board_uart = N:USART3 P:D8:7,D9 F:90

[env:g071r]
build_flags = ${env.build_flags} -DXTAL=0
board_uart = N:USART2 P:A2:U1,A3 F:64

[env:g431k]
build_flags = ${env.build_flags} -DXTAL=0
board_uart = N:USART2 P:A2:U7,A3 F:170

[env:g431r]
build_flags = ${env.build_flags} -DXTAL=0
board_uart = N:USART2 P:A2:U7,A3 F:170

[env:h743z]
board_uart = N:USART3 P:D8:7,D9 F:120

[env:l011k]
build_flags = ${env.build_flags} -DMAX_EVENTS=10 -DMAX_TIMERS=10
board_uart = N:USART2 P:A2:U4,A3 F:32

[env:l031k]
board_uart = N:USART2 P:A2:U4,A3 F:32

[env:l073r]
board_uart = N:USART2 P:A2:U4,A3 F:32

[env:l412k]
board_uart = N:USART2 P:A2:7,A15:3 F:80

[env:l412r]
board_uart = N:USART2 P:A2:7,A15:3 F:80

[env:l432k]
board_uart = N:USART2 P:A2:7,A15:3 F:80

[env:l476r]
board_uart = N:USART2 P:A2:7,A15:3 F:80

[env:l496d]
board_uart = N:USART2 P:A2:7,A3 F:80
