[platformio]
extra_configs = ../pio-common.ini
src_dir = .

[env]
extends = common

[f723d]
monitor_speed = 1000000

[env:blink]
extends = f723d

[env:lcd]
extends = f723d

[env:leds]
extends = f723d

[env:psram]
extends = f723d

[env:qspi]
extends = f723d

[recv]
build_src_filter = +<recv.cpp>
[env:recv-gpio]
extends = recv, f723d, gpio
[env:recv-poll]
extends = recv, f723d, poll
[env:recv-sync]
extends = recv, f723d, sync
[env:recv-call]
extends = recv, f723d, call

[env:wifi]
extends = f723d
