[platformio]
src_dir = .

[env]
platform = ststm32
framework = cmsis
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror
lib_deps = symlink://../..
upload_protocol = stlink
monitor_speed = 2000000

# ....d = Discovery boards
# ....k = Nucleo-32 boards
# ....r = Nucleo-64 boards
# ....z = Nucleo-144 boards

[env:f446z]
board = nucleo_f446ze
board_leds = B0 B7 B14
board_uart = N:USART3 P:D8:7,D9 F:90 D:1 L:Stream T:3 R:1 C:4,4

[env:g431k]
board = nucleo_g431kb
build_flags = ${env.build_flags} -DXTAL=0
board_leds = B8
board_uart = N:USART2 P:A2:U7,A3 F:170

[env:l031k]
board = nucleo_l031k6
board_leds = B3
board_uart = N:USART2 P:A2:U4,A3 F:32 D:1 L:Channel T:4 R:5 C:4,4 O:1
