[platformio]
# re-use the settings from all-blink
extra_configs = ../all-blink/platformio.ini
src_dir = .

[env]
platform = ststm32
framework = cmsis
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror
lib_deps = symlink://../..
upload_protocol = stlink
monitor_speed = 2000000

# ....d = Discovery boards
# ....k = Nucleo-32 boards
# ....r = Nucleo-64 boards
# ....z = Nucleo-144 boards

[env:f103r]
board_uart = N:USART2 P:A2:U1,A3 F:36

#[env:f303k]
#board_uart = N:USART2 P:A2:7,A3 F:36 D:1 L:CH T:7 R:6 C:2,2 O:1

[env:f303z]
board_uart = N:USART3 P:D8:7,D9 F:36 D:1 L:Stream T:3 R:1 C:4,4

[env:f334r]
board_uart = N:USART2 P:A2:U7,A3 F:36

[env:f407d]
board_uart = N:USART2 P:A2:U7,A3 F:84

#[env:f401r]
#board_uart = N:USART2 P:A2:U7,A3 F:42

[env:f411r]
board_uart = N:USART2 P:A2:U7,A3 F:50

[env:f412d]
board_uart = N:USART2 P:A2:U7,A3 F:50

[env:f446z]
board_uart = N:USART3 P:D8:7,D9 F:90 D:1 L:Stream T:3 R:1 C:4,4

[env:f746z]
board_uart = N:USART3 P:D8:7,D9 F:90 D:1 L:Stream T:3 R:1 C:4,4

[env:f767z]
board_uart = N:USART3 P:D8:7,D9 F:90 D:1 L:Stream T:3 R:1 C:4,4

[env:h743z]
board_uart = N:USART3 P:D8:7,D9 F:120 D:1 L:Stream T:3 R:1 C:4,4

[env:g071r]
build_flags = ${env.build_flags} -DXTAL=0
board_uart = N:USART2 P:A2:U1,A3 F:64

[env:g431k]
build_flags = ${env.build_flags} -DXTAL=0
board_uart = N:USART2 P:A2:U7,A3 F:170

[env:g431r]
build_flags = ${env.build_flags} -DXTAL=0
board_uart = N:USART2 P:A2:U7,A3 F:170

[env:l011k]
build_flags = ${env.build_flags} -DMAX_EVENTS=15
board_uart = N:USART2 P:A2:U4,A3 F:32 D:1 L:Channel T:4 R:5 C:4,4 O:1

[env:l031k]
board_uart = N:USART2 P:A2:U4,A3 F:32 D:1 L:Channel T:4 R:5 C:4,4 O:1

[env:l073r]
board_uart = N:USART2 P:A2:U4,A3 F:32 D:1 L:Channel T:4 R:5 C:4,4 O:1

[env:l412k]
board_uart = N:USART2 P:A2:7,A15:3 F:80 D:1 L:Channel T:7 R:6 C:2,2 O:1

[env:l412r]
board_uart = N:USART2 P:A2:7,A15:3 F:80 D:1 L:Channel T:7 R:6 C:2,2 O:1

[env:l432k]
board_uart = N:USART2 P:A2:7,A15:3 F:80 D:1 L:CH T:7 R:6 C:2,2 O:1

[env:l476r]
board_uart = N:USART2 P:A2:7,A15:3 F:80 D:1 L:CH T:7 R:6 C:2,2 O:1

[env:l496d]
board_uart = N:USART2 P:A2:7,A3 F:80 D:1 L:CH T:7 R:6 C:2,2 O:1
