[platformio]
extra_configs = ../pio-common.ini
src_dir = .

[env]
upload_protocol = blackmagic

[env:blink]
extends = jnzv4

[i2c]
build_src_filter = +<i2c.cpp>
[env:i2c-gpio]
extends = i2c, jnzv4, gpio
[env:i2c-poll]
extends = i2c, jnzv4, poll
[env:i2c-sync]
extends = i2c, jnzv4, sync
[env:i2c-call]
extends = i2c, jnzv4, call

[env:rtc]
extends = jnzv4

[recv]
build_src_filter = +<recv.cpp>
[env:recv-gpio]
extends = recv, jnzv4, gpio
[env:recv-poll]
extends = recv, jnzv4, poll
[env:recv-sync]
extends = recv, jnzv4, sync
[env:recv-call]
extends = recv, jnzv4, call

[spi]
build_src_filter = +<spi.cpp>
[env:spi-gpio]
extends = spi, jnzv4, gpio
[env:spi-poll]
extends = spi, jnzv4, poll
[env:spi-sync]
extends = spi, jnzv4, sync
[env:spi-call]
extends = spi, jnzv4, call

[toggle]
build_src_filter = +<toggle.cpp>
[env:toggle-gpio]
extends = toggle, jnzv4, gpio
[env:toggle-poll]
extends = toggle, jnzv4, poll
[env:toggle-sync]
extends = toggle, jnzv4, sync
[env:toggle-call]
extends = toggle, jnzv4, call

[env:uart]
extends = jnzv4
