[platformio]
src_dir = .

[env]
platform = ststm32
framework = cmsis
build_src_filter = +<${PIOENV}.cpp>
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror -Wno-format
lib_deps = symlink://../..
board = bluepill_f103c8
board_leds = C13
board_build.f_cpu = 72000000
upload_protocol = blackmagic
monitor_speed = 2000000

[env:blink]
[env:tick]
