[platformio]
src_dir = .

[env]
platform = ststm32
framework = cmsis
board = olimexino_stm32f3
board_leds = A5 A1
board_dcf = dat:A4 pon:B7 vcc:A6 gnd:A7
board_msf = dat:A14 pon:B7 vcc:A6 gnd:A7
board_rfm = d0:C0 d3:C1 rst:C2
board_lipo = adc:B0
board_can = rx:B8 tx:B9
board_usb = n:A11 p:A12 det:C11 disc:C12
board_rtc = refin:A1
board_gps = pps:B5 pwr:F4
board_uart2 = N:USART2 P:A2:7,A3 F:36 D:1 L:CH T:1 R:1 C:7,6 O:1
board_uart3 = N:USART3 P:B10:7,B11 F:36 D:2 L:CH T:2 R:2 C:2,1 O:1
board_spi1 = N:SPI1 P:A7:5,A6,A5,A4:P F:72 D:1 L:CH T:3 R:3 C:3,2 O:1
board_spi2 = N:SPI2 P:B15:5,B14,B13,D2:P F:36 D:1 L:CH T:4 R:4 C:5,4 O:1
build_src_filter = +<${PIOENV}.cpp>
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror -Wno-format
lib_deps = symlink://../..
monitor_speed = 2000000

[env:blink]
[env:fast]
[env:serial]
[env:dcf77]
