[platformio]
src_dir = .

[env]
platform = ststm32
framework = cmsis
board = genericSTM32F103RC
board_leds = D2
board_uart = N:UART5 P:C12:U1,D2 F:36
board_uart1 = N:USART1 P:A9:U1,A10 F:72 D:1 L:Channel T:4 R:5 C:2,2 O:1
board_uart2 = N:USART2 P:A2:U1,A3 F:36 D:1 L:Channel T:7 R:6 C:2,2 O:1
board_uart3 = N:USART3 P:B10:U1,B11 F:36 D:1 L:Channel T:2 R:3 C:2,2 O:1
board_uart4 = N:UART4 P:C10:U1,C11 F:36 D:2 L:Channel T:5 R:3 C:2,2 O:1
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror
lib_deps = symlink://../..
monitor_speed = 2000000

[env:main]
