# Common configuration sections for use in platformio.ini files.

[env]
platform = ststm32
framework = cmsis
build_src_filter = +<${PIOENV}.cpp>
build_flags = -std=c++17 -Wall -Werror -Wno-format
lib_deps = symlink://../..
monitor_speed = 115200

# BOARDS

[f103hy]
board = hy_tinystm103tb
board_leds = A1
board_uart = N:USART1 P:A9:7,A10 F:72 D:1 L:Channel T:4 R:5 C:0,0 O:1
board_spi = N:SPI1 P:A7:5,A6:F,A5:5,A4:P F:72 D:1 L:Channel T:3 R:2 C:0,0 O:1
board_rfm69 = dios:B5:F,B3,B4,B0,A15 nrst:A8

[f429hy]
board = disco_f429zi
build_flags = ${env.build_flags} -DXTAL=25
board_leds = B0 B1 C13 A4
board_uart = N:USART1 P:A9:7,A10 F:90 D:2 L:Stream T:7 R:5 C:4,4 O:0

[f723d]
board = disco_f723ie
build_flags = ${env.build_flags} -DXTAL=25
board_exti = IN:A3 OUT:A2
board_leds = A5 A7 B1
board_uart = N:USART6 P:C6:8,C7 F:108 D:2 L:Stream T:6 R:2 C:5,5
board_uart_l = N:USART2 P:A2:7,A3 F:108 D:1 L:Stream T:6 R:5 C:4,4
board_uart_w = N:UART5 P:C12:8,D2 F:54 D:1 L:Stream T:7 R:0 C:4,4
board_spi = N:SPI2 P:C3:5,C2,I1,I0:P F:54 D:1 L:Stream T:4 R:3 C:0,0
board_rfm69 = dios:A4:F,B0,B11,H4,H5 nrst:F11

[g431k]
board = nucleo_g431kb
build_flags = ${env.build_flags} -DXTAL=0
board_leds = B8
board_uart = N:USART2 P:A2:UH7,A3 F:170 D:1 L:CH T:1 R:2 C:27,26 O:1
board_i2c = N:I2C1 P:B7:OH4,A15 F:170 D:1 L:CH T:3 R:4 C:17,16 O:1
board_spi = N:SPI1 P:B5:H5,B4,B3,A11:HP F:170 D:1 L:CH T:3 R:4 C:11,10 O:1

[g474r]
board = nucleo_g474re
build_flags = ${env.build_flags} -DXTAL=24
board_exti = IN:C5 OUT:C4
board_leds = A5
board_uart = N:USART2 P:A2:7,A3 F:170 D:1 L:CH T:1 R:2 C:27,26 O:1
board_uart_lb = N:USART1 P:C4:7,C5 F:170 D:1 L:CH T:3 R:4 C:25,24 O:1
board_uart_lp = N:LPUART1 P:C1:8,C0 F:170 D:1 L:CH T:5 R:6 C:35,34 O:1

[l031k]
board = nucleo_l031k6
board_leds = B3
board_uart = N:USART2 P:A2:4,A15 F:32 D:1 L:Channel T:4 R:5 C:4,4 O:1
board_spi = N:SPI1 P:B5:0,B4,B3,A11:P F:32 D:1 L:Channel T:3 R:2 C:1,1 O:1
board_rfm69 = dios:A0:F,A1,A3,A8,B6 nrst:B1

[l412k]
board = nucleo_l412kb
board_leds = B3
board_uart = N:USART2 P:A2:7,A15:3 F:80 D:1 L:Channel T:7 R:6 C:2,2 O:1
board_i2c = N:I2C1 P:B7:OH4,B6 F:80 D:2 L:CH T:7 R:6 C:5,5 O:1
board_spi = N:SPI1 P:B5:H5,B4,B3,A11:HP F:80 D:1 L:Channel T:3 R:2 C:1,1 O:1

[l432k]
board = nucleo_l432kc
board_leds = B3
board_uart = N:USART2 P:A2:7,A15:3 F:80 D:1 L:CH T:7 R:6 C:2,2 O:1
board_i2c = N:I2C1 P:B7:O4,B6 F:80 D:2 L:CH T:7 R:6 C:5,5 O:1

# MODES

[gpio]
board_mode = gpio
[poll]
board_mode = poll
[sync]
board_mode = sync
[call]
board_mode = call
