# Common configuration sections for use in platformio.ini files.

[env]
platform = ststm32
framework = cmsis
build_src_filter = +<${PIOENV}.cpp>
build_flags = -std=c++17 -Wall -Werror -Wno-format
lib_deps = symlink://../..
monitor_speed = 115200

# BOARDS

[g431k]
board = nucleo_g431kb
build_flags = ${env.build_flags} -DXTAL=0
board_leds = B8
board_uart = N:USART2 P:A2:UH7,A3 F:170 D:1 L:CH T:1 R:2 C:27,26 O:1
board_i2c = N:I2C1 P:B7:OH4,A15 F:170 D:1 L:CH T:3 R:4 C:17,16 O:1
board_spi = N:SPI1 P:B5:H5,B4,B3,A11:HP F:170 D:1 L:CH T:3 R:4 C:11,10 O:1

[l031k]
board = nucleo_l031k6
board_leds = B3
board_uart = N:USART2 P:A2:4,A15 F:32 D:1 L:Channel T:4 R:5 C:4,4 O:1
board_spi = N:SPI1 P:B5:0,B4,B3,A11:P F:32 D:1 L:Channel T:3 R:2 C:1,1 O:1
board_rfm69 = dios:A0:F,A1,A3,A8,B6 nrst:B1

[l412k]
board = nucleo_l412kb
board_leds = B3
board_uart = N:USART2 P:A2:7,A15:3 F:80 D:1 L:Channel T:7 R:6 C:2,2 O:1
board_spi = N:SPI1 P:B5:H5,B4,B3,A11:HP F:80 D:1 L:Channel T:3 R:2 C:1,1 O:1

[l432k]
board = nucleo_l432kc
board_leds = B3
board_uart = N:USART2 P:A2:7,A15:3 F:80 D:1 L:CH T:7 R:6 C:2,2 O:1
board_i2c = N:I2C1 P:B7:OH4,B6 F:80 D:2 L:CH T:7 R:6 C:5,5 O:1

# MODES

[gpio]
board_mode = gpio
[poll]
board_mode = poll
[sync]
board_mode = sync
[call]
board_mode = call
