[platformio]
src_dir = .

[env]
platform = ststm32
framework = cmsis
board = disco_f723ie
build_src_filter = +<${PIOENV}.cpp>
board_exti = IN:A3 OUT:A2
board_leds = A5 A7 B1
board_uart_c = N:USART6 P:C6:8,C7 F:108 D:2 L:Stream T:6 R:2 C:5,5
board_uart_j = N:USART2 P:A2:7,A3 F:108 D:1 L:Stream T:6 R:5 C:4,4
board_uart_e = N:UART5 P:C12:8,D2 F:54 D:1 L:Stream T:7 R:0 C:4,4
board_spi = N:SPI2 P:C3:5,C2,I1,I0:P F:54 D:1 L:Stream T:4 R:3 C:0,0
build_flags = -std=c++17 -Wall -Werror -Wno-format -DXTAL=25
lib_deps = symlink://../..
board_build.f_cpu = 216000000
monitor_speed = 115200

[env:blink]
[env:leds]
[env:poll]
