[platformio]
extra_configs = ../etc/common.ini
src_dir = ../../old-tests/basic

[env]
platform_packages = platformio/tool-pyocd
debug_tool = custom
extends = common
board = nucleo_h743zi
board_exti = IN:G9 OUT:G14
board_leds = B0 B7 B14
#board_uartc = N:USART3 P:D8:7,D9 F:120 D:1 L:STR T:1 R:2 C:46,45
board_uartc = N:USART3 P:D8:7,D9 F:120
board_uart = N:USART6 P:G14:7,G9 F:120 D:1 L:STR T:3 R:4 C:72,71
board_build.f_cpu = 400000000
upload_command = st-flash --reset --connect-under-reset write $SOURCE 0x20000200
monitor_port = /dev/cu.usbmodem144403
