[platformio]
src_dir = .

[env]
platform = ststm32
framework = cmsis
board = disco_f769ni
build_src_filter = +<${PIOENV}.cpp>
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror -Wno-format -DXTAL=25
board_leds = J5
board_uart = N:USART1 P:A9:7,A10 F:108 D:2 L:Stream T:7 R:5 C:4,4
lib_deps = symlink://../..
board_build.f_cpu = 200000000
monitor_speed = 115200

[env:blink]
[env:uart]
[env:ram]
