[platformio]
src_dir = .

[env]
platform = ststm32
framework = cmsis
board = disco_f429zi
build_src_filter = +<${PIOENV}.cpp>
board_leds = B0 B1 C13 A4
board_uart = N=USART1 P=A9:7,A10 F=90 D=2 L=Stream T=7 R=5 C=4,4 O=0
build_flags = -std=c++17 -Wall -Werror -Wno-format -DXTAL=25
lib_deps = symlink://../..
upload_protocol = jlink
monitor_speed = 115200
#upload_flags = -c, adapter serial 066EFF565251887067065644
#monitor_port = hwgrep://066EFF565251887067065644

[env:gpio]
[env:ram]
[env:lcd]
