[platformio]
extra_configs = ../etc/common.ini
src_dir = ../../tests/basic

[env]
extends = common
board = nucleo_f103rb
board_exti = A10 A9
board_leds = A5
#board_uart = N=USART2 P=A2:7,A3 F=36 D=1 L=Channel T=7 R=6 C=0,0 O=1
board_uart = N=USART1 P=A9:7,A10 F=72 D=1 L=Channel T=4 R=5 C=0,0 O=1
board_build.f_cpu = 72000000
