[platformio]
# re-use the settings from 1-blink and 5-task
extra_configs = ../5-task/platformio.ini

# ....d = Discovery boards
# ....k = Nucleo-32 boards
# ....r = Nucleo-64 boards
# ....z = Nucleo-144 boards
