[platformio]
src_dir = .

[env]
platform = ststm32
framework = cmsis
build_src_filter = +<${PIOENV}.cpp>
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror -Wno-format
lib_deps = symlink://../..
# f746z
board = nucleo_f746zg
board_leds = B0
board_build.f_cpu = 216000000
monitor_speed = 1000000

[env:blink]
[env:tick]
