[platformio]
default_envs = blink
src_dir = .

[env]
platform = ststm32
framework = cmsis
board = nucleo_g431kb
build_src_filter = +<${PIOENV}.cpp>
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror -Wno-format -DXTAL=0 -Itest
lib_deps = symlink://../.., unity
monitor_speed = 10625000
test_speed = 10625000

[env:blink]
[env:fast]
[env:serial]
