[platformio]
default_envs = g431k
src_dir = .

[env]
targets = upload
platform = ststm32
framework = cmsis
board = nucleo_g431kb
board_build.f_cpu = 160000000
build_src_filter = +<${PIOENV}.cpp>
build_flags =
  -std=c++17 -Wall -Wextra -Wpedantic -Werror -Wno-format -DXTAL=0
lib_deps = symlink://../..
monitor_speed = 10000000
test_speed = 10000000

[env:g431k]
# dummy, only used for "pio test"
lib_deps = symlink://../.., unity

[env:blink]
[env:fast]
[env:serial]
