[platformio]
src_dir = .

[env]
platform = ststm32
framework = cmsis
build_src_filter = +<${PIOENV}.cpp>
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror -Wno-format
lib_deps = symlink://../..
# f393o
board = olimexino_stm32f3
board_leds = A1
board_build.f_cpu = 72000000
monitor_speed = 2000000

[env:blink]
[env:tick]
[env:dcf77]
