[platformio]
src_dir = .

[env]
platform = ststm32
framework = cmsis
build_src_filter = +<${PIOENV}.cpp>
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror -Wno-format
lib_deps = symlink://../..
# f303o
board = olimexino_stm32f3
board_leds = A5 A1
board_uart1 = N:USART1 P:A9:7,A10 F:72 D:1 L:CH T:4 R:5 C:2,2 O:1
board_uart2 = N:USART2 P:A2:7,A3 F:36 D:1 L:CH T:7 R:6 C:2,2 O:1
board_build.f_cpu = 72000000
monitor_speed = 1000000

[env:blink]
[env:tick]
[env:dcf77]
[env:msf60]
[env:gps]
[env:stream]
[env:app]
