[platformio]
src_dir = .

[env]
platform = ststm32
framework = cmsis
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror
lib_deps = symlink://../..

##############################################  Discovery boards

[env:f723dis]
board = disco_f723ie
build_flags = ${env.build_flags} -DLED='"B1"'

[env:f750dis]
board = disco_f750n8
build_flags = ${env.build_flags} -DLED='"I1"'

[env:g031dis]
board = disco_g031j6
build_flags = ${env.build_flags} -DLED='"A12"'
upload_port = /Volumes/NODE_G031J6

##############################################  Nucleo-32 boards

[env:g431n32]
board = nucleo_g431kb
build_flags = ${env.build_flags} -DLED='"B8"'

[env:l031n32]
board = nucleo_l031k6
build_flags = ${env.build_flags} -DLED='"B3"'

[env:l432n32]
board = nucleo_l432kc
build_flags = ${env.build_flags} -DLED='"B3"'

##############################################  Nucleo-64 boards

[env:f103n64]
board = nucleo_f103rb
build_flags = ${env.build_flags} -DLED='"A5"'

[env:g431n64]
board = nucleo_g431rb
build_flags = ${env.build_flags} -DLED='"A5"'

##############################################  Nucleo-144 boards

[env:f303n144]
board = nucleo_f303ze
build_flags = ${env.build_flags} -DLED='"B0"'

[env:f439n144]
board = nucleo_f439zi
build_flags = ${env.build_flags} -DLED='"B0"'
