[platformio]
src_dir = .

[env]
platform = ststm32
framework = cmsis
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror
lib_deps = symlink://../..

#############################################  Discovery boards

[env:f407d]
board = disco_f407vg
build_flags = ${env.build_flags} -DLED='"D12"'

[env:f412d]
board = disco_f412zg
build_flags = ${env.build_flags} -DLED='"E0"'

[env:f429d]
board = disco_f429zi
build_flags = ${env.build_flags} -DLED='"G13"'

[env:f469d]
board = disco_f469ni
build_flags = ${env.build_flags} -DLED='"G6"'

[env:f723d]
board = disco_f723ie
build_flags = ${env.build_flags} -DLED='"B1"'

[env:f750d]
board = disco_f750n8
build_flags = ${env.build_flags} -DLED='"I1"'

[env:f769d]
board = disco_f769ni
build_flags = ${env.build_flags} -DLED='"J5"'

[env:g031d]
board = disco_g031j6
build_flags = ${env.build_flags} -DLED='"A12"'
upload_port = /Volumes/NODE_G031J6

[env:l053d]
board = disco_l053c8
build_flags = ${env.build_flags} -DLED='"B4"'
upload_port = /Volumes/NODE_G031J6

[env:l496d]
board = disco_l496ag
build_flags = ${env.build_flags} -DLED='"B13"'
upload_port = /Volumes/NODE_G031J6

#############################################  Nucleo-32 boards (STM32...K...)

[env:g431k]
board = nucleo_g431kb
build_flags = ${env.build_flags} -DLED='"B8"'

[env:l011k]
board = nucleo_l011k4
build_flags = ${env.build_flags} -DLED='"B3"'

[env:l031k]
board = nucleo_l031k6
build_flags = ${env.build_flags} -DLED='"B3"'

[env:l412k]
board = nucleo_l412kb
build_flags = ${env.build_flags} -DLED='"B3"'

[env:l432k]
board = nucleo_l432kc
build_flags = ${env.build_flags} -DLED='"B3"'

#############################################  Nucleo-64 boards (STM32...R...)

[env:f103r]
board = nucleo_f103rb
build_flags = ${env.build_flags} -DLED='"A5"'

[env:f302r]
board = nucleo_f302r8
build_flags = ${env.build_flags} -DLED='"B13"'

[env:f334r]
board = nucleo_f334r8
build_flags = ${env.build_flags} -DLED='"A5"'

[env:f401r]
board = nucleo_f401re
build_flags = ${env.build_flags} -DLED='"A5"'

[env:f411r]
board = nucleo_f411re
build_flags = ${env.build_flags} -DLED='"A5"'

[env:g431r]
board = nucleo_g431rb
build_flags = ${env.build_flags} -DLED='"A5"'

[env:l053r]
board = nucleo_l053r8
build_flags = ${env.build_flags} -DLED='"A5"'

[env:l073r]
board = nucleo_l073rz
build_flags = ${env.build_flags} -DLED='"A5"'

[env:l412r]
board = nucleo_l412rb_p
build_flags = ${env.build_flags} -DLED='"B13"'

[env:l433r]
board = nucleo_l433rc_p
build_flags = ${env.build_flags} -DLED='"B13"'

[env:l476r]
board = nucleo_l476rg
build_flags = ${env.build_flags} -DLED='"A5"'

#############################################  Nucleo-144 boards (STM32...Z...)

[env:f303z]
board = nucleo_f303ze
build_flags = ${env.build_flags} -DLED='"B0"'

[env:f413z]
board = nucleo_f413zh
build_flags = ${env.build_flags} -DLED='"B0"'

[env:f439z]
board = nucleo_f439zi
build_flags = ${env.build_flags} -DLED='"B0"'

[env:f722z]
board = nucleo_f722ze
build_flags = ${env.build_flags} -DLED='"B0"'

[env:f746z]
board = nucleo_f746zg
build_flags = ${env.build_flags} -DLED='"B0"'

[env:f767z]
board = nucleo_f767zi
build_flags = ${env.build_flags} -DLED='"B0"'

[env:h743z]
board = nucleo_h743zi
build_flags = ${env.build_flags} -DLED='"B0"'
