[platformio]
src_dir = .

[env]
platform = ststm32
framework = cmsis
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror
lib_deps = symlink://../..

#############################################  Discovery boards

[env:f407d]
board = disco_f407vg
board_leds = D12

[env:f412d]
board = disco_f412zg
board_leds = E0

[env:f429d]
board = disco_f429zi
board_leds = G13

[env:f469d]
board = disco_f469ni
board_leds = G6

[env:f723d]
board = disco_f723ie
board_leds = B1

[env:f750d]
board = disco_f750n8
board_leds = I1

[env:f769d]
board = disco_f769ni
board_leds = J5

[env:g031d]
board = disco_g031j6
board_leds = A12
upload_port = /Volumes/NODE_G031J6

[env:l053d]
board = disco_l053c8
board_leds = B4

[env:l475d]
board = disco_l475vg_iot01a
board_leds = A5

[env:l496d]
board = disco_l496ag
board_leds = B13

#############################################  Nucleo-32 boards (STM32...K...)

[env:g431k]
board = nucleo_g431kb
board_leds = B8

[env:l011k]
board = nucleo_l011k4
board_leds = B3

[env:l031k]
board = nucleo_l031k6
board_leds = B3

[env:l412k]
board = nucleo_l412kb
board_leds = B3

[env:l432k]
board = nucleo_l432kc
board_leds = B3

#############################################  Nucleo-64 boards (STM32...R...)

[env:f103r]
board = nucleo_f103rb
board_leds = A5

[env:f302r]
board = nucleo_f302r8
board_leds = B13

[env:f334r]
board = nucleo_f334r8
board_leds = A5

[env:f401r]
board = nucleo_f401re
board_leds = A5

[env:f411r]
board = nucleo_f411re
board_leds = A5

[env:g431r]
board = nucleo_g431rb
board_leds = A5

[env:l053r]
board = nucleo_l053r8
board_leds = A5

[env:l073r]
board = nucleo_l073rz
board_leds = A5

[env:l412r]
board = nucleo_l412rb_p
board_leds = B13

[env:l433r]
board = nucleo_l433rc_p
board_leds = B13

[env:l476r]
board = nucleo_l476rg
board_leds = A5

#############################################  Nucleo-144 boards (STM32...Z...)

[env:f303z]
board = nucleo_f303ze
board_leds = B0

[env:f413z]
board = nucleo_f413zh
board_leds = B0

[env:f439z]
board = nucleo_f439zi
board_leds = B0

[env:f722z]
board = nucleo_f722ze
board_leds = B0

[env:f746z]
board = nucleo_f746zg
board_leds = B0

[env:f767z]
board = nucleo_f767zi
board_leds = B0

[env:h743z]
board = nucleo_h743zi
board_leds = B0
