[platformio]
src_dir = .

[env]
platform = ststm32
framework = cmsis
build_src_filter = +<${PIOENV}.cpp>
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror -Wno-format -DXTAL=0
lib_deps = symlink://../..
board = nucleo_g431rb
board_leds = A5
board_uart = N:USART2 P:A2:U7,A3 F:170 D:1 L:CH T:1 R:2 C:27,26 O:1
board_uarta = N:USART1 P:C4:U7,C5 F:170 D:1 L:CH T:3 R:4 C:25,24 O:1
board_uartb = N:USART3 P:B9:U7,B8 F:170 D:1 L:CH T:5 R:6 C:29,28 O:1
board_uartc = N:UART4 P:C10:U5,C11 F:170 D:2 L:CH T:1 R:2 C:31,30 O:1
board_uartd = N:LPUART1 P:C1:U8,C0 F:170 D:2 L:CH T:3 R:4 C:35,34 O:1
board_build.f_cpu = 160000000
monitor_speed = 1000000

[env:serial]
