[platformio]
extra_configs = ../pio-common.ini
src_dir = .

[l031k]
board = nucleo_l031k6
board_leds = B3
board_uart = N:USART2 P:A2:4,A15 F:32 D:1 L:Channel T:4 R:5 C:4,4 O:1
board_spi = N:SPI1 P:B5:0,B4,B3,A11:P F:32 D:1 L:Channel T:3 R:2 C:1,1 O:1
board_rfm69 = dios:A0:F,A1,A3,A8,B6 nrst:B1

[env:blink]
extends = l031k

[recv]
build_src_filter = +<recv.cpp>
[env:recv-gpio]
extends = recv, l031k, gpio
[env:recv-poll]
extends = recv, l031k, poll
[env:recv-sync]
extends = recv, l031k, sync
[env:recv-call]
extends = recv, l031k, call
