[platformio]
src_dir = .

[env]
platform = ststm32
framework = cmsis
board = nucleo_l031k6
build_src_filter = +<${PIOENV}.cpp>
board_leds = B3
board_uart = N:USART2 P:A2:4,A15 F:32 D:1 L:Channel T:4 R:5 C:4,4 O:1
board_spi = N:SPI1 P:B5:0,B4,B3,A11:P F:32 D:1 L:Channel T:3 R:2 C:1,1 O:1
board_rfm69 = dios:A0:F,A1,A3,A8,B6 nrst:B1
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror -Wno-format
lib_deps = symlink://../..
monitor_speed = 115200

[env:blink]
[env:poll]
