[platformio]
src_dir = .

[env]
platform = ststm32
framework = cmsis
board = nucleo_l031k6
build_src_filter = +<${PIOENV}.cpp>
board_leds = B3
board_uart = N=USART1 P=A9:7,A10 F=72 D=1 L=Channel T=4 R=5 C=0,0 O=1
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror
lib_deps = symlink://../..
monitor_speed = 115200

[env:blink]
