[platformio]
extra_configs = ../pio-common.ini
src_dir = .

[env]
extends = common

[endure]
build_src_filter = +<endure.cpp>
[env:endure-gpio]
extends = endure, g431k, gpio
[env:endure-poll]
extends = endure, g431k, poll
[env:endure-sync]
extends = endure, g431k, sync
[env:endure-call]
extends = endure, g431k, call

[env:rand]
extends = g431k, poll

[spif]
build_src_filter = +<spif.cpp>
[env:spif-gpio]
extends = spif, g431k, gpio
[env:spif-poll]
extends = spif, g431k, poll
[env:spif-sync]
extends = spif, g431k, sync
[env:spif-call]
extends = spif, g431k, call
