[platformio]
src_dir = .

[env]
platform = ststm32
framework = cmsis
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror
lib_deps = symlink://../..
upload_protocol = stlink

# ....d = Discovery boards
# ....k = Nucleo-32 boards
# ....r = Nucleo-64 boards
# ....z = Nucleo-144 boards

[env:f103bp]
board = bluepill_f103c8
board_leds = C13
upload_protocol = blackmagic

[env:f103hy]
board = hy_tinystm103tb
board_leds = A1
upload_protocol = blackmagic

[env:f103o]
board = olimexino
board_leds = A5 A1

[env:f103r]
board = nucleo_f103rb
board_leds = A5

[env:f103rc]
# see https://stm32-base.org/boards/STM32F103RCT6-Generic-Board
board = genericSTM32F103RC
board_leds = D2

[env:f302r]
board = nucleo_f302r8
board_leds = B13

[env:f303k]
board = nucleo_f303k8
board_leds = B3

[env:f303o]
board = olimexino_stm32f3
board_leds = A5 A1

[env:f303z]
board = nucleo_f303ze
board_leds = B0 B7 B14

[env:f334r]
board = nucleo_f334r8
board_leds = A5

[env:f401r]
board = nucleo_f401re
board_leds = A5

[env:f407d]
board = disco_f407vg
board_leds = D12

[env:f411bp]
board = blackpill_f411ce
board_leds = C13

[env:f411r]
board = nucleo_f411re
board_leds = A5

[env:f412d]
board = disco_f412zg
board_leds = E0

[env:f413z]
board = nucleo_f413zh
board_leds = B0 B7 B14

[env:f429d]
board = disco_f429zi
board_leds = G13

[env:f439z]
board = nucleo_f439zi
board_leds = B0 B7 B14

[env:f446z]
board = nucleo_f446ze
board_leds = B0 B7 B14

[env:f469d]
board = disco_f469ni
board_leds = G6

[env:f722z]
board = nucleo_f722ze
board_leds = B0 B7 B14

[env:f723d]
board = disco_f723ie
board_leds = B1

[env:f746z]
board = nucleo_f746zg
board_leds = B0 B7 B14

[env:f750d]
board = disco_f750n8
board_leds = I1

[env:f767z]
board = nucleo_f767zi
board_leds = B0 B7 B14

[env:f769d]
board = disco_f769ni
board_leds = J5

[env:g031d]
board = disco_g031j6
board_leds = A12

[env:g071r]
board = nucleo_g071rb
board_leds = A5

[env:g431k]
board = nucleo_g431kb
board_leds = B8

[env:g431r]
board = nucleo_g431rb
board_leds = A5

[env:g474r]
board = nucleo_g474re
board_leds = A5

[env:h743z]
board = nucleo_h743zi
board_leds = B0 B7 B14

[env:l011k]
board = nucleo_l011k4
board_leds = B3

[env:l031k]
board = nucleo_l031k6
board_leds = B3

[env:l053d]
board = disco_l053c8
board_leds = B4

[env:l053r]
board = nucleo_l053r8
board_leds = A5

[env:l073r]
board = nucleo_l073rz
board_leds = A5

[env:l412k]
board = nucleo_l412kb
board_leds = B3

[env:l412r]
board = nucleo_l412rb_p
board_leds = B13

[env:l432k]
board = nucleo_l432kc
board_leds = B3

[env:l433r]
board = nucleo_l433rc_p
board_leds = B13

[env:l452r]
board = nucleo_l452re
board_leds = A5

[env:l475d]
board = disco_l475vg_iot01a
board_leds = A5

[env:l476r]
board = nucleo_l476rg
board_leds = A5

[env:l496d]
board = disco_l496ag
board_leds = B13

[env:wl55r]
board = nucleo_wl55jc
board_leds = B15
build_flags = ${env.build_flags} -DCORE_CM4
