[platformio]
src_dir = .

[env]
platform = ststm32
framework = cmsis
board = nucleo_l432kc
build_src_filter = +<${PIOENV}.cpp>
build_flags = -std=c++17 -Wall -Werror -Wno-format
lib_deps = symlink://../..
upload_flags = -c, adapter serial 0669FF555052836687022922
monitor_port = hwgrep://0669FF555052836687022922
monitor_speed = 115200
board_leds = B3
board_uart = N:USART2 P:A2:7,A15:3 F:80 D:1 L:CH T:7 R:6 C:2,2 O:1

[env:blink]
[env:stop]
[env:alarm]
[env:coma]
[env:minimal]
