[platformio]
src_dir = .

[env]
platform = ststm32
framework = cmsis
build_src_filter = +<${PIOENV}.cpp>
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror -Wno-format
lib_deps = symlink://../..
# f413z
board = nucleo_f413zh
board_leds = B0 B7 B14
board_uart  = N:USART3  P:D8:U7,D9    F:50  D:1 L:Stream T:3 R:1 C:4,4
board_uart1  = N:USART1 P:B6:U7,B3    F:100 D:2 L:Stream T:7 R:2 C:4,4
board_uart2  = N:USART2 P:A2:U7,A3    F:50  D:1 L:Stream T:6 R:5 C:4,4
board_uart4  = N:UART4  P:A0:U8,C11   F:50  D:1 L:Stream T:4 R:2 C:4,4
board_uart5  = N:UART5  P:C12:U8,D2   F:50  D:1 L:Stream T:7 R:0 C:8,4
board_uart6  = N:USART6 P:G14:U8,G9   F:100 D:2 L:Stream T:6 R:1 C:5,5
board_uart9  = N:UART9  P:D15:U11,D14 F:100 D:2 L:Stream T:0 R:7 C:1,0
board_uart10 = N:UART10 P:E3:U11,E2   F:100 D:2 L:Stream T:5 R:3 C:9,9
board_build.f_cpu = 100000000
monitor_speed = 1000000

[env:blink]
[env:uarts]
[env:tick]
