# SVD fixes

[IOREG]
SCB = 0xE000ED00
STK = 0xE000E010

[IOREG:STM32F1]
SYSCFG = AFIO

[IOREG:STM32L0]
SYSCFG = SYSCFG_COMP

[IRQ:STM32F1]
DMA2_Channel5 = DMA2_Channel4_5

[IRQ:STM32F3]
EXTI2 = EXTI2_TSC

[IRQ:STM32F411]
DMA1_Stream0 = 11
DMA1_Stream1 = 12
DMA1_Stream2 = 13
DMA1_Stream3 = 14
DMA1_Stream4 = 15
DMA1_Stream5 = 16
DMA1_Stream6 = 17
DMA1_Stream7 = 47
DMA2_Stream0 = 56
DMA2_Stream1 = 57
DMA2_Stream2 = 58
DMA2_Stream3 = 59
DMA2_Stream4 = 60
DMA2_Stream5 = 68
DMA2_Stream6 = 69
DMA2_Stream7 = 70
USART1 = 37
USART2 = 38
USART6 = 71

[IRQ:STM32G0]
DMA1_Channel1 = DMA_Channel1
DMA1_Channel2 = DMA_Channel2_3
DMA1_Channel3 = DMA_Channel2_3
DMA1_Channel4 = DMA_Channel4_5_6_7
DMA1_Channel5 = DMA_Channel4_5_6_7
DMA1_Channel6 = DMA_Channel4_5_6_7
DMA1_Channel7 = DMA_Channel4_5_6_7
I2C1_EV = I2C1
I2C1_ER = I2C1

[IRQ:STM32G4]
LPUART1 = LPUART

# see dma.h - only some H7's?
#[IRQ:STM32H7]
#DMAMUX = DMAMUX1

[IRQ:STM32L0]
DMA1_Channel2 = DMA1_Channel2_3
DMA1_Channel3 = DMA1_Channel2_3
DMA1_Channel4 = DMA1_Channel4_7
DMA1_Channel5 = DMA1_Channel4_7
DMA1_Channel6 = DMA1_Channel4_7
DMA1_Channel7 = DMA1_Channel4_7
I2C1_EV = I2C1
I2C1_ER = I2C1

[RCC:STM32G0]
IOPENR = 0x34

[RCC:STM32L0]
IOPENR = 0x2C

[ENA:STM32F1]
SYSCFG = AFIO

[ENA:STM32F3]
GPIOA = 17 AHBENR

[ENA:STM32F413]
UART9 = 6 APB2ENR
UART10 = 7 APB2ENR

[ENA:STM32G0]
GPIOA = 0 IOPENR

[ENA:STM32G4]
DAC1 = 16 AHB2ENR
DAC2 = 17 AHB2ENR
DAC3 = 18 AHB2ENR
DAC4 = 19 AHB2ENR

[ENA:STM32L0]
GPIOA = 0 IOPENR
