[platformio]
src_dir = .

[env]
platform = ststm32
framework = cmsis
build_src_filter = +<${PIOENV}.cpp>
build_flags = -std=c++17 -Wall -Werror -Wno-format -DXTAL=0
lib_deps = symlink://../..
board_build.f_cpu = 170000000
monitor_speed = 1000000
# G413
board = nucleo_g431kb
board_leds = B8
board_uart = N:USART2 P:A2:UH7,A3 F:170 D:1 L:CH T:1 R:2 C:27,26 O:1
board_spi = N:SPI1 P:B5:H5,B4,B3,A11:HP F:170 D:1 L:CH T:3 R:4 C:11,10 O:1
# L412
#board = nucleo_l412kb
#board_leds = B3
#board_uart = N:USART2 P:A2:7,A15:3 F:80 D:1 L:Channel T:7 R:6 C:2,2 O:1
#board_spi = N:SPI1 P:B5:H5,B4,B3,A11:HP F:80 D:1 L:Channel T:3 R:2 C:1,1 O:1

[env:spif]
