[platformio]
extra_configs = ../pio-common.ini
src_dir = .

# APPS

[endure]
build_src_filter = +<endure.cpp>
[spif]
build_src_filter = +<spif.cpp>

# BUILD TARGETS

[env:rand]
extends = g431k, poll

[env:endure-gpio]
extends = g431k, endure, gpio
[env:endure-poll]
extends = g431k, endure, poll
[env:endure-sync]
extends = g431k, endure, sync
[env:endure-call]
extends = g431k, endure, call

[env:spif-gpio]
extends = g431k, spif, gpio
[env:spif-poll]
extends = g431k, spif, poll
[env:spif-sync]
extends = g431k, spif, sync
[env:spif-call]
extends = g431k, spif, call
