[platformio]
extra_configs = ../pio-common.ini
src_dir = .

[env]
extends = common

[g431k]
board_uart2 = N:USART1 P:A9:7,A10 F:170 D:1 L:CH T:1 R:2 C:25,24 O:1

[send]
build_src_filter = +<send.cpp>
[env:send-poll]
extends = send, g431k, poll
[env:send-sync]
extends = send, g431k, sync
[env:send-call]
extends = send, g431k, call
