[platformio]
# re-use the settings from 1-blink
extra_configs = ../1-blink/platformio.ini

[env]
monitor_speed = 115200

# ....d = Discovery boards
# ....k = Nucleo-32 boards
# ....r = Nucleo-64 boards
# ....z = Nucleo-144 boards

[env:f103r]
board_serout = dev::USART2 pin:A2:7 ver:1

[env:f103rc]
board_serout = dev::UART5 pin:C12:1 ver:1

[env:f303k]
board_serout = dev::USART2 pin:A2:7

[env:f303o]
board_serout = dev::USART3 pin:B10:7

[env:f303z]
board_serout = dev::USART3 pin:D8:7

[env:f334r]
board_serout = dev::USART2 pin:A2:7

[env:f401r]
board_serout = dev::USART2 pin:A2:7 ver:1

[env:f407d]
board_serout = dev::USART2 pin:A2:7 ver:1

[env:f411bp]
board_serout = dev::USART1 pin:A9:7 ver:1

[env:f411r]
board_serout = dev::USART2 pin:A2:7 ver:1

[env:f412d]
board_serout = dev::USART2 pin:A2:7 ver:1

[env:f413z]
board_serout = dev::USART3 pin:D8:7

[env:f446z]
board_serout = dev::USART3 pin:D8:7 ver:1

[env:f746z]
board_serout = dev::USART3 pin:D8:7

[env:f750d]
board_serout = dev::USART1 pin:A9:7

[env:f767z]
board_serout = dev::USART3 pin:D8:7

[env:g071r]
board_serout = dev::USART2 pin:A2:1

[env:g431k]
board_serout = dev::USART2 pin:A2:7

[env:g431r]
board_serout = dev::USART2 pin:A2:7

[env:h743z]
board_serout = dev::USART3 pin:D8:7

[env:l011k]
board_serout = dev::USART2 pin:A2:4

[env:l031k]
board_serout = dev::USART2 pin:A2:4

[env:l073r]
board_serout = dev::USART2 pin:A2:4

[env:l412k]
board_serout = dev::USART2 pin:A2:7

[env:l412r]
board_serout = dev::USART2 pin:A2:7

[env:l432k]
board_serout = dev::USART2 pin:A2:7

[env:l476r]
board_serout = dev::USART2 pin:A2:7

[env:l496d]
board_serout = dev::USART2 pin:A2:7
