[platformio]
src_dir = .

[common]
platform = ststm32
framework = cmsis
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror -Wno-format -g
lib_deps = symlink://../..
monitor_speed = 115200

[env:f439z]
extends = common
board = nucleo_f439zi
monitor_port = hwgrep://066CFF515049657187154330
upload_flags = -c, adapter serial 066CFF515049657187154330

board_ether = A1:PH11,A2,A7,C1,C4,C5,G11,G13,B13
board_leds = B0 B7 B14
board_uart = N=USART3 P=D8:7,D9 F=45 D=1 L=Stream T=3 R=1 C=4,4

[env:f429hy]
extends = common
board = disco_f429zi
upload_protocol = jlink
build_flags = ${common.build_flags} -DXTAL=25

board_ether = A1:PH11,A2,A7,C1,C4,C5,G11,G13,G14,A8:PV0
board_leds = B0 B1 C13
board_uart = N=USART1 P=A9:7,A10 F=90 D=2 L=Stream T=7 R=5 C=4,4 O=0
