[platformio]
src_dir = .

[env]
platform = ststm32
framework = cmsis
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror -Wno-format
lib_deps = symlink://../..
upload_protocol = stlink
monitor_speed = 115200

# ....d = Discovery boards
# ....k = Nucleo-32 boards
# ....r = Nucleo-64 boards
# ....z = Nucleo-144 boards

[env:f413z]
board = nucleo_f413zh
board_leds = B0 B7 B14
board_serout = dev::USART3 pin:D8:7

[env:f446z]
board = nucleo_f446ze
board_leds = B0 B7 B14
board_serout = dev::USART3 pin:D8:7 VER:1

[env:g431k]
board = nucleo_g431kb
board_leds = B8
board_serout = dev::USART2 pin:A2:7

[env:l011k]
board = nucleo_l011k4
board_leds = B3
board_serout = dev::USART2 pin:A2:4

[env:l412k]
board = nucleo_l412kb
board_leds = B3
board_serout = dev::USART2 pin:A2:7
