[platformio]
src_dir = .

[env]
platform = ststm32
framework = cmsis
build_src_filter = +<${PIOENV}.cpp>
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror -Wno-format
lib_deps = symlink://../..
board = nucleo_f303ze
board_leds = B0 B7 B14
board_uart1 = N:USART1 P:C4:7,C5 F:72 D:1 L:CH T:4 R:5 C:2,2 O:1
board_uart3 = N:USART3 P:D8:7,D9 F:36 D:1 L:CH T:2 R:3 C:2,2 O:1
board_spi1 = N:SPI1 P:A7:5,A6:P,A5:5,D14:P F:72 D:1 L:CH T:3 R:2 C:1,1 O:1
board_build.f_cpu = 72000000
monitor_speed = 2000000

[env:blink]
[env:tick]
[env:gps]
[env:lcd]
