[platformio]
src_dir = .

[env]
platform = ststm32
framework = cmsis
build_src_filter = +<${PIOENV}.cpp>
build_flags =
  -std=c++17 -Wall -Wextra -Wpedantic -Werror -Wno-format -DXTAL=0 -DTRACE -I.
lib_deps = symlink://../..
board = nucleo_g431kb
board_leds = B8
board_trace =
  I:A12 S:B0 R:B6 D:A7 P:A15 x:B7 y:A4 z:A1 0:A0 1:A8 2:A11 3:B3 4:B5 5:B4
board_uart = N:USART2 P:A2:U7,A3 F:170 D:1 L:CH T:1 R:2 C:27,26 O:1
board_uartx = N:USART1 P:B6:U7,A10 F:170 D:1 L:CH T:3 R:4 C:25,24 O:1
board_build.f_cpu = 160000000
monitor_speed = 2000000

[env:pins]
[env:async]
[env:block]
