[platformio]
src_dir = .

[env]
platform = ststm32
framework = cmsis
build_src_filter = +<${PIOENV}.cpp>
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror -Wno-format -DXTAL=0
lib_deps = symlink://../..
board = nucleo_f303k8
board_leds = B3
monitor_speed = 2000000

[env:blink]
[env:tick]
