[platformio]
src_dir = .

[env]
platform = ststm32
framework = cmsis
build_src_filter = +<${PIOENV}.cpp>
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror -Wno-format
lib_deps = symlink://../..
board = nucleo_f446ze
board_leds = B0 B7 B14
board_uart1 = N:USART6 P:G14:8,G9 F:180 D:2 L:Stream T:7 R:1 C:5,5
board_uart3 = N:USART3 P:D8:7,D9 F:90 D:1 L:Stream T:3 R:1 C:4,4
board_spi1 = N:SPI1 P:A7:5,A6,A5,D14:P F:90 D:2 L:Stream T:3 R:2 C:3,3
monitor_speed = 2000000

[env:gps]
[env:lcd]
