[platformio]
src_dir = .

[env]
platform = ststm32
framework = cmsis
build_src_filter = +<${PIOENV}.cpp>
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror -Wno-format
lib_deps = symlink://../..
board = nucleo_f446ze
board_leds = B0 B7 B14
monitor_speed = 115200

[env:blink]
[env:tick]
