[platformio]
extra_configs = ../pio-common.ini
src_dir = .

[f103hy]
upload_protocol = stlink

[env:blink]
extends = f103hy

[recv]
build_src_filter = +<recv.cpp>
[env:recv-gpio]
extends = recv, f103hy, gpio
[env:recv-poll]
extends = recv, f103hy, poll
[env:recv-sync]
extends = recv, f103hy, sync
[env:recv-call]
extends = recv, f103hy, call
