[platformio]
src_dir = .

[env]
platform = ststm32
framework = cmsis
board = hy_tinystm103tb
build_src_filter = +<${PIOENV}.cpp>
board_leds = A1
board_uart = N=USART1 P=A9:7,A10 F=72 D=1 L=Channel T=4 R=5 C=0,0 O=1
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror -Wno-format
lib_deps = symlink://../..
upload_protocol = stlink
monitor_speed = 115200

[env:blink]
