[platformio]
src_dir = .

[env]
platform = ststm32
framework = cmsis
board = hy_tinystm103tb
build_src_filter = +<${PIOENV}.cpp>
board_leds = A1
board_uart = N:USART1 P:A9:7,A10 F:72 D:1 L:Channel T:4 R:5 C:0,0 O:1
board_spi = N:SPI1 P:A7:5,A6:F,A5:5,A4:P F:72 D:1 L:Channel T:3 R:2 C:0,0 O:1
board_rfm69 = dios:B5:F,B3,B4,B0,A15 nrst:A8
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror -Wno-format
lib_deps = symlink://../..
upload_protocol = stlink
monitor_speed = 115200

[env:blink]
[env:poll]
