[platformio]
#src_dir = ../../tests/unit

[env]
platform = ststm32
framework = cmsis
board = nucleo_g431kb
board_leds = B8
board_serio = A9:7,A10
board_uart = N=USART2 P=A2:7,A3 F=16 D=1 L=CH O=0 T=3 R=1 C=27,26
build_src_filter = +<${PIOENV}.cpp>
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror -Wno-format
board_build.ldscript = ram.ld
lib_deps = symlink://../..
upload_protocol = custom
extra_scripts = post:pio-extra.py

[env:t01-itm]
[env:t02-dump]
[env:t03-led]
[env:t04-jumper]
[env:t05-serio]
[env:t06-logf]
