[platformio]
#src_dir = ../../tests/unit

[env]
platform = ststm32
framework = cmsis

board = nucleo_g431kb
board_exti = A10 A9
board_leds = B8
board_serio = A9:7,A10
#board_uart = N=USART2 V=2 P=A2:7,A3 F=150 D=1 L=CH O=0 T=1 R=2 C=26,27
board_uart = N=USART1 V=2 P=A9:7,A10 F=150 D=1 L=CH O=0 T=1 R=2 C=24,25

board_build.f_cpu = 150000000
board_build.ldscript = ram.ld
build_src_filter = +<${PIOENV}-*.cpp>
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror -Wno-format -g -DXTAL=0
lib_deps = symlink://../..
upload_protocol = custom
monitor_speed = 115200
extra_scripts = post:pio-extra.py

[env:t00]
[env:t01]
[env:t02]
[env:t03]
[env:t04]
[env:t05]
[env:t06]
[env:t07]
[env:t08]
[env:t09]
[env:t10]
[env:t11]
[env:t12]
[env:t13]
[env:t14]
[env:t15]
[env:t16]
