[platformio]
src_dir = ../../tests/unit

[env]
platform = ststm32
framework = cmsis
board = nucleo_g431kb
board_leds = B8
build_src_filter = +<${PIOENV}.cpp>
build_flags = -std=c++17 -Wall -Wextra -Wpedantic -Werror -Wno-format
lib_deps = symlink://../..
upload_protocol = custom
extra_scripts = pio-extra.py

[env:basic]
